apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fin-app-microservice-1-component
  description: Microservice-1 of the Financial App
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=fin-app-ms-1'
spec:
  type: service
  lifecycle: experimental
  owner: fin-app-ms-1-team